// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Aramis.TrainMovementData.Data
{
    public partial class Delay
    {
        public long Id { get; set; }
        public string TrainNumber { get; set; }
        public DateTime Date { get; set; }
        public string DelayType { get; set; }
        public string StationShort { get; set; }
        public string Station { get; set; }
        public TimeSpan? ActualTime { get; set; }
        public int? CauseId { get; set; }
        public int? ProportionateDelayMinutes { get; set; }
        public string DelayTrainNumber { get; set; }
        public int? DelayMinutes { get; set; }
        public DateTime? DisruptionDate { get; set; }
        public string Region { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }

        public virtual BasicData BasicData { get; set; }
    }
}