// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Aramis.TrainMovementData.Data
{
    public partial class Modification
    {
        public long Id { get; set; }
        public string TrainNumber { get; set; }
        public DateTime Date { get; set; }
        public string ModificationType { get; set; }
        public short? ModeOfModification { get; set; }
        public string StationShortFrom { get; set; }
        public string StationFrom { get; set; }
        public string StationShortTo { get; set; }
        public string StationTo { get; set; }
        public string Track { get; set; }
        public string TemplateTrainnumber { get; set; }
        public int? AdditionalDelay { get; set; }
        public TimeSpan? ReferenceTime { get; set; }
        public DateTime? DisruptionDate { get; set; }
        public string Region { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }

        public virtual BasicData BasicData { get; set; }
    }
}