// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Aramis.TrainMovementData.Data
{
    public partial class SectionOfLine
    {
        public long Id { get; set; }
        public string TrainNumber { get; set; }
        public DateTime Date { get; set; }
        public string SectionOfLineType { get; set; }
        public string StationShort { get; set; }
        public string Station { get; set; }
        public TimeSpan? TimeScheduled { get; set; }
        public TimeSpan? TimeActual { get; set; }
        public string Line { get; set; }
        public string ExceptionalSending { get; set; }
        public int? WeightCarriage { get; set; }
        public int? LengthTotal { get; set; }
        public short? NumberOfCarriages { get; set; }
        public string TractionVeihicle1 { get; set; }
        public string TractionVehicle2 { get; set; }
        public string TractionVehicle3 { get; set; }
        public int? MaxVelocity { get; set; }
        public int? MinBreakWeightPercentage { get; set; }

        public virtual BasicData BasicData { get; set; }
    }
}