// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Aramis.TrainMovementData.Data
{
    public partial class BasicData
    {
        public BasicData()
        {
            Delay = new HashSet<Delay>();
            Modification = new HashSet<Modification>();
            Notification = new HashSet<Notification>();
            Remark = new HashSet<Remark>();
            SectionOfLine = new HashSet<SectionOfLine>();
            Vehicle = new HashSet<Vehicle>();
        }

        public string TrainNumber { get; set; }
        public DateTime Date { get; set; }
        public string TrainCategory { get; set; }
        public string TrainQuality { get; set; }
        public string TrainIdentifier { get; set; }
        public string Line { get; set; }
        public string Orderer { get; set; }
        public string Operator { get; set; }
        public string TractionProvider { get; set; }
        public string TrainType { get; set; }
        public int? LengthTotal { get; set; }
        public int? LengthCarriage { get; set; }
        public int? WeightTotal { get; set; }
        public int? WeightCarriage { get; set; }
        public int? Velocity { get; set; }
        public int? BreakWeightPercentage { get; set; }
        public string ReferenceStationShort { get; set; }
        public TimeSpan? RefereneTime { get; set; }
        public bool? MidnightJump { get; set; }
        public string Filename { get; set; }

        public virtual ICollection<Delay> Delay { get; set; }
        public virtual ICollection<Modification> Modification { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
        public virtual ICollection<Remark> Remark { get; set; }
        public virtual ICollection<SectionOfLine> SectionOfLine { get; set; }
        public virtual ICollection<Vehicle> Vehicle { get; set; }
    }
}