// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Aramis.TrainMovementData.Data
{
    public partial class Log
    {
        public int Id { get; set; }
        public string TrainNumber { get; set; }
        public DateTime? Date { get; set; }
        public string FileTrainNumber { get; set; }
        public DateTime? FileDate { get; set; }
        public string FileName { get; set; }
        public byte Type { get; set; }
        public string Text { get; set; }
        public string StackTrace { get; set; }
    }
}