// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Aramis.TrainMovementData.Data
{
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string TrainNumber { get; set; }
        public DateTime Date { get; set; }
        public string VehicleType { get; set; }
        public string StationShortFrom { get; set; }
        public string StationShortTo { get; set; }
        public string CarriageVehicleNumber { get; set; }
        public string CarriageVehicleType { get; set; }
        public int? WeightEmpty { get; set; }
        public int? WeightLoad { get; set; }
        public int? Length { get; set; }
        public int? MaxVelocity { get; set; }
        public string RestaurantCar { get; set; }
        public string Info { get; set; }

        public virtual BasicData BasicData { get; set; }
    }
}